workflow = 'add_controller.json'
SKIP_TASKS = """
primary-rabbitmq
cluster_health
generate_vms
vmware-vcenter
top-role-cinder-vmware
top-role-compute-vmware
cluster-vrouter
virtual_ips
conntrackd
ceph_create_pools
ceph_ready_check
enable_rados
updatedb
primary-dns-server
dns-server
upload_cirros
dump_rabbitmq_definitions
ntp-server
primary-cluster-haproxy
restart-haproxy
connectivity_tests
openstack-haproxy
openstack-haproxy-horizon
openstack-haproxy-keystone
openstack-haproxy-nova
openstack-haproxy-heat
openstack-haproxy-glance
openstack-haproxy-cinder
openstack-haproxy-neutron
openstack-haproxy-mysqld
openstack-haproxy-swift
openstack-haproxy-radosgw
openstack-haproxy-ceilometer
openstack-haproxy-aodh
openstack-haproxy-sahara
openstack-haproxy-murano
openstack-haproxy-stats
openstack-haproxy-ironic
primary-database
primary-controller
primary-mongo
create-cinder-types
primary-openstack-controller
primary-openstack-network-plugins-l2
openstack-network-plugins-l2
primary-openstack-network-agents-l3
openstack-network-agents-l3
primary-openstack-network-agents-dhcp
openstack-network-agents-dhcp
primary-openstack-network-agents-metadata
openstack-network-agents-metadata
primary-heat
heat
heat-db
heat-keystone
ironic-api
ironic-db
ironic-keystone
ironic-compute
primary-keystone
keystone
keystone-db
generate_changed_admin_user
copy_changed_admin_user
delete_old_admin_user
top-role-primary-mongo
horizon
""".split()